# Forward Configuration
# Format: source_channel_id -> destination_channel_id with language and text replacements

forwards:
  # -1002635367492:
  #   dest: -1003484865062
  #   lang: fr
  #   replace:
  #     "@finstrasupport": "@goldaiofficialsupport"
  #     FINSTRA: GOLD AI

  # -1002477064021:
  #   dest: -1003490790931
  #   lang: fr
  #   replace:
  #     "@finstrasupport": "@goldaiofficialsupport"
  #     FINSTRA: GOLD AI

  - source: -1002477064021
    dest: -1003490790931
    lang: spanish
    replace:
      "@finstrasupport": "@goldaiofficialsupport"
      "FINSTRA": "GOLD AI"
      "FINTRA": "GOLD AI"

  - source: -1002477064021
    dest: -1003654063319
    lang: spanish
    replace:
      "@finstrasupport": "@finstra_soporte"

  - source: -1002477064021
    dest: -1003292935094
    lang: romanian
    replace:
      "@finstrasupport": "@Asistenta_Finstra"

  - source: -1002477064021
    dest: -1003775416979
    lang: en
    replace:
      "@finstrasupport": "@Dave_passiveprofits"
      "finstra": "PASSIVE PROFITS"

